### ISSUE TITLE
install-daemon.py: Failed to enable unit

### ISSUE THREAD

**Issue by blueyed** [albertz/mouse-scroll-wheel-acceleration-userspace#7]
I've tried the install-daemon script, but it failed, apparently due to a mismatch in the path (`default.target.wants/` part)!?

```
% ./install-daemon.py
Writing default config file to /home/user/.config/mouse-scroll-wheel-accelerator/config.py
Writing systemd config to /home/user/.config/systemd/user/mouse-scroll-wheel-accelerator.service:
Failed to enable unit: Unit file /home/user/.config/systemd/user/default.target.wants/mouse-scroll-wheel-accelerator.service does not exist.
Something has gone wrong... you might want to use 'journalctl --user -u mouse-scroll-wheel-accelerator.service' to debug
Traceback (most recent call last):
  File "…/Vcs/mouse-scroll-wheel-acceleration-userspace/./install-daemon.py", line 75, in <module>
    main()
  File "…/Vcs/mouse-scroll-wheel-acceleration-userspace/./install-daemon.py", line 71, in main
    setup(args)
  File "…/Vcs/mouse-scroll-wheel-acceleration-userspace/./install-daemon.py", line 62, in setup
    raise e
  File "…/Vcs/mouse-scroll-wheel-acceleration-userspace/./install-daemon.py", line 57, in setup
    systemd('enable', unit_name)
  File "…/Vcs/mouse-scroll-wheel-acceleration-userspace/./install-daemon.py", line 37, in systemd
    method(['systemctl', '--no-pager', '--user', *args])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['systemctl', '--no-pager', '--user', 'enable', 'mouse-scroll-wheel-accelerator.service']' returned non-zero exit status 1.
```

(using systemd 250 (250.3-1-arch))

**Comment by blueyed** [comment]
Maybe it needs to ensure the path `~/.config/systemd/user/default.target.wants` is created (as a dir)?

**Comment by albertz** [comment]
But it does that. The code is:
```python
  unit_name = args.unit_name
  systemd_user_dir = Path(f'~/.config/systemd/user').expanduser()
  systemd_user_dir.mkdir(parents=True, exist_ok=True)
  out = systemd_user_dir / unit_name
  print(f"Writing systemd config to {out}:")

  server_bin = Path(__file__).absolute().parent / 'main.py'
  out.write_text(_SystemdConfigTemplate.format(service_name=common.app_name_human, server=server_bin))

  try:
    systemd('stop', unit_name, ignore_errors=True)  # ignore errors here if it wasn't running in the first place
    systemd('daemon-reload')
    systemd('enable', unit_name)
    systemd('start', unit_name)
    systemd('status', unit_name)
  except Exception as e:
    print(f"Something has gone wrong... you might want to use 'journalctl --user -u {unit_name}' to debug")
    raise e
```

There you see the `systemd_user_dir.mkdir`.
And then it writes the file via `out.write_text`.

However, the `systemd_user_dir` (`/home/user/.config/systemd/user`) is apparently wrong. It seems to look into `/home/user/.config/systemd/user/default.target.wants` instead.

This is strange because I think for me, `systemd_user_dir` was correct. I don't know enough about systemd to tell which systemd user dir is the correct one. Do you know more about this?

**Comment by blueyed** [comment]
`systemd_user_dir` is just `~/.config/systemd/user/`, not `…/default.target.wants` (where the symlink gets created by systemd-enable).

I think the service unit should be installed like it is, but enabling requires the `….target.wants` dir to exist (which seems a bit strange, since it could be created on demand - not sure about this).

However, I've figured that systemd is not really fit to manage this for me, given that I two X.org servers typically, and even with the above caveat worked around it was failing already due to missing `$DISPLAY` information.

Therefore I've just (re-)added it to `~/.xinitrc` / `~/.xprofile`.

Some more resources: https://superuser.com/questions/759759/writing-a-service-that-depends-on-xorg/1128905#1128905 and https://wiki.archlinux.org/title/Systemd/User.

**Comment by albertz** [comment]
> I think the service unit should be installed like it is, but enabling requires the `….target.wants` dir to exist (which seems a bit strange, since it could be created on demand - not sure about this).

Yea, this is strange. I don't think that I needed to do this. So why do you need that now?

But anyway, you say we should just add:
```python
(systemd_user_dir / "default.target.wants").mkdir(parents=True, exist_ok=True)
```
?

**Comment by blueyed** [comment]
Yes.
Check your `~/.config/systemd/user/` - you probably have it there already.
If you disable the service (and it is the last) the dir gets removed for me also again.

**Comment by albertz** [comment]
Ok I added that.
